Restaurant main page with tabs
pbkabali/Restaurant-Page pull request #1
Opened 2020-11-30 20:28 UTC by pbkabali

This implements the restaurant page with the following tabs:

- Home
- Menu
- Contact

2020-11-30 21:35 UTC, lekegitrepo requested changes
## Status: Request changes :recycle:
#### Hi @pbkabali :clap: :clap:
#### You have done a good job :+1: The module separation is impressive, the project is organized and structure in a manner that can be easily understood. However, some aspects of the code were not handled appropriately. Check the review summary and comments below :point_down:

#### Disabled ESLint:
- **_Avoid usage of `/*eslint disable*/`_**

#### _Reviewed by Temitayo Adeleke_

2020-11-30 21:35 UTC, lekegitrepo commented on src/index.js
> +/* eslint-disable*/
- **_Fix the lint error(or disable an error, avoid overuse of linter disable) instead of disabling eslint on the whole file_**

2020-11-30 21:35 UTC, lekegitrepo commented on src/nav.js
> +/* eslint-disable*/
- **_Fix the lint error(or disable an error, avoid overuse of linter disable) instead of disabling eslint on the whole file_**

2020-11-30 21:35 UTC, lekegitrepo commented on src/nav.js
> +/* eslint-disable*/
- **_Fix the lint error(or disable an error, avoid overuse of linter disable) instead of disabling eslint on the whole file_**

2020-11-30 21:35 UTC, lekegitrepo commented on src/pageLoad.js
> +/* eslint-disable*/
- **_Fix the lint error(or disable an error, avoid overuse of linter disable) instead of disabling eslint on the whole file_**

2020-11-30 21:35 UTC, lekegitrepo commented on src/pageLoad.js
> +/* eslint-disable*/
- **_Fix the lint error(or disable an error, avoid overuse of linter disable) instead of disabling eslint on the whole file_**

2020-11-30 22:11 UTC, pbkabali commented
Dear @lekegitrepo, thank you so much for the feedback. I fixed the linting error and submitted another review request. Thanks a lot

2020-11-30 23:30 UTC, trekab approved these changes
### Approved! :tada: 
Congratulations @pbkabali! Nice job modularizing your code with ES6 modules! You may proceed to your next project. Keep up the good work! :+1: 

__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-12-01 00:40 UTC, pbkabali commented
Thank you very much for your review, @trekab

2020-12-01 00:42 UTC, merged